DigitalHack/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('only_app.urls')),
    url(r'^admin/', admin.site.urls),
]

only_app/urls.py
from django.conf.urls import url

from . import views


app_name = 'only_app'
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for home-page:
    url(r'^$', views.index, name='index'),

    #url for
    url(r'^yo1$', views.ansible, name='ansible'),

    #url
    url(r'^term$', views.getTer, name='getTer'),

    #url
    url(r'^terminal$', views.openTer, name='openTer'),

    #url
    url(r'^editsave$', views.editsave, name='editsave'),
    
    #url for login:
    url(r'^login$', views.login, name='login')    
    ]

only_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

only_app/forms.py
from django import forms

class GitLink(forms.Form):
    link=forms.CharField(max_length = 100)
    pname= forms.CharField(max_length=80)

class IP(forms.Form):
    inp=forms.CharField(max_length=80)
    #out=forms.CharField(max_length=80)

class Saver(forms.Form):
    out=forms.CharField(max_length=200)
    nm=forms.CharField(max_length=200)

only_app/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
import os
import subprocess
import json
from django.urls import reverse

from .api_do import my_server
from only_app.forms import GitLink,IP,Saver

serv=my_server()

def index(request):
    auth = request.body
    access_token = request.GET.get('code')
    
    if access_token == None:
        return HttpResponseRedirect(reverse('only_app:login'))
    else:
        serv.api_token=access_token
        request.session['access_token'] = access_token
    
    return render( request, 'Temp/main.html')

def control_panel( request):
    
    #power-on existing or new server    
    if request.GET.get( 'droplet')!=None:
        d_id = request.GET.get( 'code')
        serv.open_server( d_id)
    else:
        serv.new_server()
    serv.server_on()

    #authenticate
    link = serv.server_get_ip
    subprocess.call( ["ssh", "root@", link ])


def login(request):
    login_link=my_server.login_link

    return render(request, 'Temp/login.html', {'login_link': login_link })

def openTer(request):
    if request.method == 'POST':
        ip=IP(request.POST)
        if ip.is_valid():

            inp=ip.cleaned_data.get('inp')
            out=" "
            inp=inp.split()
            if inp[0]=="cd":
                os.chdir(inp[1])
            elif (inp[0]=="gedit")or(inp[0]=="vim")or(inp[0]=="nano"):
                #pop=subprocess.Popen("cat < "+inp[1])
                file=open(inp[1])
                pop=file.read()
                file.close()
                return render(request, 'Temp/editer.html',{"fnm":inp[1],"pop":pop})
            else:
                p=subprocess.Popen(inp, stdout=subprocess.PIPE)
                out, err = p.communicate()

            return render(request, 'Temp/term.html', {"out":out})
        else:
            return HttpResponse("Form not valid")
    else:
        return render(request, 'Temp/term.html', {"out": " "})



def ansible(request):
    #os.system("ls")
    return HttpResponse("running")

def getTer(request):
    if request.method == 'POST':
        gitlink=GitLink(request.POST)
        if gitlink.is_valid():
            link = gitlink.cleaned_data.get('link')
            pname= gitlink.cleaned_data.get('pname')
        else:
            return HttpResponse("Form not valid")
    subprocess.call(["git","clone",link])
    os.chdir(pname)
    subprocess.call(["ls"])
    return HttpResponseRedirect(reverse('only_app:openTer'))

"""
def editer(request):
    p = subprocess.Popen(, stdout=subprocess.PIPE)

    return render(request, 'Temp/editer.html')

def getTer(request):
    #server code
    serv=my_server()
    if(i==1):
        #new server         
        serv.server_create()
        did=serv.droplet.id #to save in database, this is droplet id
        serv.server_on()
        subprocess.call(["ssh","root@",link])
    elif(i==2):
        #restore server
    #to here
    if request.method == 'POST':
        if gitlink!=None            
            gitlink=GitLink(request.POST)
            if gitlink.is_valid():
                link = gitlink.cleaned_data.get('link')
                pname= gitlink.cleaned_data.get('pname')
            subprocess.call(["git","clone",link])
            os.chdir(pname)
            subprocess.call(["ls"])
    return render
"""


def editsave(request):
    if request.method == 'POST':
        s= Saver(request.POST)
        if s.is_valid():
            wrt=s.cleaned_data.get('out')
            fnm=s.cleaned_data.get('nm')
            file=open(fnm,'w')
            file.write(wrt)
            file.close()

    return render(request, 'Temp/term.html', {"out": " "})

only_app/templates/Temp/control_panel.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>DigitalHack</title>
		<meta name="generator" content="Bootply" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">

		 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' %}" rel="stylesheet" type="text/css">

	</head>
	<body>
<!--login modal-->
<header id="top" class="header">
        <div class="text-vertical-center">
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h1 class="text-center">DigitalHack</h1>
        </div>


        <div class="modal-body">
            <title> DROPLETS CHOOSE</title>
            {% for i in droplets %}  
                <a href="{% url 'only_app:control_panel' %}?droplet={{i.did}}">{{i.name}}</a>
            {% end for %}
        </div>
        <div class="modal-body">
            <title> Create new Droplet </title>
            <form class="form col-md-12 center-block" method="POST" action="{% url 'only_app:control_panel' %}">
			{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="link" placeholder="droplet name" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="pname" placeholder="Github project name" required>
            </div>
            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block">Submit</button>
            </div>
          </form>
        </div>

    </div>
</div>

</div>
</header>
</body>
</html>

only_app/templates/Temp/editer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>DigitalHack</title>
		<meta name="generator" content="Bootply" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">

		 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' %}" rel="stylesheet" type="text/css">

	</head>


<body>
<!--login modal-->
<header id="top" class="header">
        <div class="text-vertical-center">
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Editer</h1>
      </div>


      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="{% url 'only_app:editsave' %}">
			{% csrf_token %}
        <div style="float:left" width=100%>
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="nm" placeholder="Enter file name:" required>
            </div>

        </div>

        <div style="float:left" width=100%>
        <textarea rows="20" cols="50" placeholder="Output" width=100% name="out">{{ pop }}</textarea>

        </div>

            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block">save</button>

            </div>
          </form>
      </div>
      <div class="modal-footer">

      </div>
  </div>
  </div>
</div>
</div>
</header>
	</body>
</html>

only_app/templates/Temp/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>DigitalHack</title>
		<meta name="generator" content="Bootply" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">

		 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' %}" rel="stylesheet" type="text/css">

	</head>
	<body>
<!--login modal-->
<header id="top" class="header">
        <div class="text-vertical-center">
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">DigitalHack</h1>
      </div>


      <div class="modal-body">
          <a href="{{login_link}}">Login</a>
      </div>


      <div class="modal-footer">
      </div>
  </div>
  </div>
</div>

</div>
</header>
</body>
</html>

only_app/templates/Temp/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>DigitalHack</title>
		<meta name="generator" content="Bootply" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">

		 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' %}" rel="stylesheet" type="text/css">

	</head>
	<body>








<!--login modal-->
<header id="top" class="header">
        <div class="text-vertical-center">
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">DigitalHack</h1>
      </div>


      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="{% url 'only_app:getTer' %}">
			{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="link" placeholder="Github clone link" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="pname" placeholder="Github project name" required>
            </div>
              <!--
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="Username" placeholder="User Name" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control input-lg" name="ip" placeholder="IP-address" required>
            </div>
            <div class="form-group">
              <input type="password" class="form-control input-lg" name="pwd" placeholder="Password" required>
            </div>-->
            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block">Submit</button>
              <!--<span class="pull-right"><a href="signup.html">Register</a></span>
			  <span><a href="#">Need help?</a></span>-->
            </div>
          </form>
      </div>


      <div class="modal-footer">
      </div>
  </div>
  </div>
</div>

</div>
</header>
</body>
</html>

only_app/templates/Temp/term.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>DigitalHack</title>
		<meta name="generator" content="Bootply" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">

		 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic' %}" rel="stylesheet" type="text/css">

	</head>

    <!--<body>

    <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="{% url 'only_app:openTer' %}">
			{% csrf_token %}

    <div>

    <div style="float:left" width=100%>
        <div width=100%>

            <textarea rows="4" cols="50" placeholder="Input" name="input"></textarea>

        </div>
        
        <div class="form-group">
            <button class="btn btn-primary btn-lg btn-block">Submit</button>

        </div>
    </div>
    <div style="float:left" width=100%>
        <textarea rows="4" cols="50" placeholder="Output" width=100% name="out">{{ out }}</textarea>

    </div>

    </div>

    </form>
    </div>

    <div class="form-group" style="width:30%;color:red">
          <button class="btn btn-warning btn-lg btn-block">Close</button>

    </div>

</body>-->

<body>
<!--login modal-->
<header id="top" class="header">
        <div class="text-vertical-center">
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Terminal</h1>
      </div>
      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="{% url 'only_app:openTer' %}">
			{% csrf_token %}
	    <div class="form-group">
              <input type="text" class="form-control input-lg" name="inp" placeholder="input" required>
            </div>
        <div style="float:left" width=100%>
        <textarea rows="12" cols="50" placeholder="Output" width=100% name="out">{{ out }}</textarea>

        </div>

            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block">submit</button>

            </div>
          </form>
      </div>
      <div class="modal-footer">

      </div>
  </div>
  </div>
</div>
</div>
</header>
	</body>
</html>